ALTER TABLE `example`.`PLACE` 
ADD COLUMN `ARRIVALDATE` DATETIME NULL AFTER `IMGURLS`,
ADD COLUMN `DEPARTUREDATE` DATETIME NULL AFTER `ARRIVALDATE`,
ADD COLUMN `ADDRESS` VARCHAR(255) NULL AFTER `DEPARTUREDATE`,
ADD COLUMN `COORDINATES` VARCHAR(45) NULL AFTER `ADDRESS`;
