ALTER TABLE `example`.`PLACE` 
ADD COLUMN `ISBOOKED` INT NULL AFTER `COUNTRY`,
ADD COLUMN `FREECANCELLATIONDATE` DATETIME NULL AFTER `ISBOOKED`,
ADD COLUMN `ISOPTIONAL` INT NULL AFTER `FREECANCELLATIONDATE`;
